Tidy up: centralise parser loader so this can be called by data_type
openghg/openghg pull request #1095
Opened 2024-08-13 16:41 UTC by rt17603

* **Summary of changes** (Bug fix, feature, docs update, ...)

Similarly to #1094 , this adds two new functions which allow the parse function itself to be loaded by supplying the `data_type` and `source_format` and uses these within the relevant store classes. This is, again, so that only the data_type input is needed to ensure the correct details can be accessed within the read_file and transform_data methods. The specific functions e.g. `load_surface_parser` have been removed.

The two functions are:
 - `openghg.util.load_standardise_parser`
 - `openghg.util.load_transform_parser`

This impacts the same data_type objects as PR #1094 .

For the `Footprints` object this had to have some additional small changes as the standardise sub-module was called `footprint` (singular) but the data_type was called `footprints` meaning these two did not match. Change made:
 - Renamed standardise sub-module to `footprints` rather than `footprint` (likewise with tests)

*Note: I did not relocate these parsers in this PR but they may be off within `openghg.standardise` if this doesn't cause circular imports when accessing this from `openghg.store`*

* **Please check if the PR fulfills these requirements**

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [ ] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

2024-08-15 13:01 UTC, brendan-m-murphy requested changes
Looks good, although I think the parser loading functions shouldn't be in `util` since they're only used by `store`. It might make sense to have them in `store` or in `standardise` with the parsers, since they provide access to the parsers (this would be my preference).

2024-08-15 14:47 UTC, brendan-m-murphy commented on openghg/util/_file.py
>      "load_parser",
Ah sorry I didn't see that comment. No it doesn't have to happen in this PR. I'll approve.

2024-08-15 14:47 UTC, brendan-m-murphy submitted a review, later dismissed

2024-08-15 17:00 UTC, rt17603 commented on openghg/util/_file.py
>      "load_parser",
That's fine - it's a good suggestion and I think we will need to do it at some point.

2024-08-16 08:29 UTC, brendan-m-murphy approved these changes
Reapproving after merging in devel

2024-08-16 08:31 UTC, merged