Adding initial obspack creation logic
openghg/openghg pull request #1117
Opened 2024-09-06 16:38 UTC by rt17603

* **Summary of changes** (Bug fix, feature, docs update, ...)

* **Please check if the PR fulfills these requirements**

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [ ] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

2025-01-07 13:55 UTC, brendan-m-murphy requested changes
Looks good overall. There are some typos that need to be fixed, and there are some bigger points I'm not clear on (but the answer might be "that is what obspacks look like").

2025-01-07 13:55 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    output_file.write(f"File created: {pd.to_datetime('today').normalize}\n")
```suggestion
    output_file.write(f"File created: {pd.to_datetime('today').normalize()}\n")
```

2025-01-07 13:55 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    be incuded within the dataset attributes.
```suggestion
    be included within the dataset attributes.
```

2025-01-07 13:55 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    site_details = df.groupby(site_column).apply(collate_strings)
This raises a warning (for me at least): DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

Seems like `include_groups=False` should fix it?

2025-01-07 13:55 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    site_details = df.groupby(site_column).apply(collate_strings)
The site details don't seem to include the species of gas. For the search df in the tutorial, the co2 and ch4 results at TAC are combined into a single row. 

I guess there are two things I'm unclear on:
1. should the species be included?
2. why are the rows compressed like this?  It looks like this is meant to be human readable, and the comma separated lists inside the fields might make it hard to read if these lists are long.

Also, should there be a copy of the original search df/csv included for reproducibility?

2025-01-08 14:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +        site_insitu/
I think this should actually be `surface-insitu` and `surface-flask` - I'll correct them both.

2025-01-08 14:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +*Version included within the site filenames is currently just the version for the obspack but should be updated
What metadata would you be thinking for this? Each nc file should have attributes which contains the key details at least?

2025-01-08 14:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +This will create a new obspack with a version based on other folder which have the same
> There's sort of weird behaviour if say, you make an obspack called "test_obspack", then make a second version using "test_obspack" as the stub. Then the second version has _v1 at the end, and the first obspack created has no version at the end.

Yeah you're right it does do this which may seem a bit strange - what would be an alternative though do you think? I don't think we'd want to rename the first obspack but would we just want to start the next one as v2 perhaps?

> Inside both of these obspacks, the filenames end with _v1.

Yeah at the moment it default to v1 if no version is specified and then uses v1 when it's version 1 - again this could perhaps be solved by making it `test_obspack` and then `test_obspack_v2` right off the bat but also see below.

Overall though I see this as 2 things:
1. How external obspack version number should behave
2. How internal versions are set
  - Really the *version* of the obspack and the *version* for the file shouldn't need to be connected at all e.g. as per the comment included above "Version included within the site filenames is currently just the version for the obspack but should be updated to be the object store internal version" so maybe if I just added that change now it would solve this second issue at least.

2025-01-08 14:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +                   obspack_name=obspack_name,
Ah yep you're right (thought I'd caught those)

```suggestion
                   obspack_stub=obspack_stub,
```

2025-01-08 14:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +                   obspack_name=obspack_name,
```suggestion
                   obspack_stub=obspack_stub,
```

2025-01-08 14:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +    create_obspack(search_df=search_df,
Yeah the `create_obspack` function should return the `obspack_path` and `output_folder` is the parent folder for this. Did you think anything else needed adding around this e.g. in the documentation?

2025-01-10 15:39 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +This will create a new obspack with a version based on other folder which have the same
Ok I've addressed (2) by updating this to now use the internal data version rather than the obspack version.

For (1) I could take a look at updating this so that if "test_obspack" is found, it then created "test_obspack_v2" as the next obspack?

2025-01-10 15:46 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    site_details = df.groupby(site_column).apply(collate_strings)
Yeah the idea with the site details file basically to include a quick summary of just the site information so the measurement owner could be contacted if people who had the obspack needed to do so. I think we can work on making it more human readable as needed but I think I prefer the tabular format for now as a summary? I can look into if splitting by header rows could make this easier / see the data team what they'd prefer.

Overall, we should work to ensure the attributes for each file contain the more exhaustive list of details needed for the data.

2025-01-14 11:52 UTC, brendan-m-murphy approved these changes
Looks good! I included some suggested improvements, but they don't need to happen now.

2025-01-14 11:52 UTC, brendan-m-murphy commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +This will create a new obspack with a version based on other folder which have the same
I guess adding numbers for files that would have the same name is kind of default on some operating systems (like if you download the same file twice), so `test_obspack`, `test_obspack_v1` isn't that weird really.

I think changing the versions for the file is good though, since it reduces redundant info and avoids that weird corner case.

Anyway, happy to leave (1) alone.

2025-01-14 11:52 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        include_version: Whether to include the data version in the filename. Default = True.
Just a thought: If the data is for external use, then this internal object store version might be confusing. (OTOH, at some point we discussed exporting UUIDs and versions so that we know exactly what data was used. Maybe that can go in some kind of "manifest" file describing what is in the obspack.)

2025-01-14 11:52 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    site_details = df.groupby(site_column).apply(collate_strings)
Okay, we can leave it as is. I guess a nested tabular structure like I suggested would be harder to work with in code, so maybe not worth trying unless necessary.

2025-01-14 11:52 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        output_name = define_obspack_filename(
It might be worth checking that there are no duplicate file names before starting to write the data.

I guess the intention is to avoid this, but it seems possible to include data from the same species/site/inlet but different instruments or sources.

Checking for duplicate output filepaths could be a fairly easy way to check this. (And would preempt a later more confusing error when `.to_netcdf` complains.)

2025-01-14 11:52 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        ds = data.data
You could parallelise this easily with dask "bags" if you like. Maybe after validating file names, make a dask "bag" containing tuples: `(ds, output_name)` and then apply a function like `lambda x: x[0].to_netcdf(x[1])`. If the output files are all unique, then you can just write everything in parallel.

(If you do this, you would probably want to use a different loop to make the `site_details_df`.)

(Also, it might be better to make the bag contain tuples `(obs_data, output_name)` and use `.map` with `lambda x: x[0].data.to_netcdf(x[1])`, since calling `.data` might trigger something that dask would like to know about.)

2025-01-14 11:52 UTC, brendan-m-murphy commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +    create_obspack(search_df=search_df,
I just meant that doing, e.g.
```
result = create_obspack(search_filename=output_folder / "search_config.csv", output_folder=output_folder, obspack_name=obspack_name)
!ls -R {result}
```
 is handy.

But you don't need to include this if you don't want to. You give an alternate way to do it below.

2025-01-14 11:52 UTC, brendan-m-murphy commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +*Version included within the site filenames is currently just the version for the obspack but should be updated
At some point we discussed recording actual UUIDs and versions for the data. I guess this and the search metadata should be enough for reproducibility. This doesn't have to be included now.

2025-01-14 11:56 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        include_version: Whether to include the data version in the filename. Default = True.
When we were thinking from observation data perspective the idea around it was that the version in the object store would represent the reprocessed version of the data so e.g. v1 would be the initial data, then it would be reprocessed externally after some additional calibration (v2) etc. It would also help to distinguish between previous obspacks e.g. this new obspack contains an updated version of the data.

Its absolutely not a perfect assumption and requires good maintenance of an object store but that was the logic at least. We can see how that works in practice though.

2025-01-14 12:02 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +*Version included within the site filenames is currently just the version for the obspack but should be updated
Yeah you're right - I'll make a note on the umbrella issue so we don't forget to do this as I think it would be valuable.

2025-01-17 09:56 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    site_details = df.groupby(site_column).apply(collate_strings)
Thanks for catching that - should be added now

2025-01-17 10:21 UTC, rt17603 commented on doc/source/tutorials/local/Outputting_data/Creating_obspack.rst
> +This will create a new obspack with a version based on other folder which have the same
I've updated this now so it does treat `test_obspack` as version 1 and so the next version will be `test_obspack_v2` - I think that does seem like a reasonable update to make and can always change it back if people using it decide the old way was better.

2025-02-24 17:20 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        output_name = define_obspack_filename(
I've put in quite a few changes to try and address this. It basically does the following:
 - creates the output names (based on name_components - e.g. ["species", "site", "inlet"]
 - checks for duplicate names
 - if duplicates are present, creates new output names based on additional metakeys from data_type config e.g. ["species", "site", "inlet", "data_level"]

As part of this initial draft, to do this I started to construct an object to hold some of these details - `StoredData` as it got a bit complex trying to link the filename and metadata otherwise. This is still fairly minimal but can be expanded upon in future versions as needed.

Caveat: one known issue at the moment is that because the filename also includes the version it can see two filenames as different if the two data sources have different versions even if the other keys match. I can try and address that in this PR but can leave that for now as a corner case.

2025-02-25 13:25 UTC, brendan-m-murphy reviewed
The new naming stuff looks really nice.

There's a lot of code here. I think it might be easier to understand if the code modelled the ObsPack more closely.

The code could broadly split into two phases:
1. parse the search input to make the obspack structure (which would be represented in an `ObsPack` object)
2. write out the data

Obviously this is what the code is already doing, but the point would be to focus on building the obs pack structure in the code using objects. Right now it feels like the structure is encoded in many functions that pass file paths around. 

In addition to your `StoredData` object, you could have a `Collection` object (in the comments, I suggested `ObsPack` and `Subfolder` objects, although they both share some common features) that contains `StoreData` and other `Collection` objects. Basically, the `Collection` object is like a folder, and the `StoredData` object is like a file.

Also, maybe some of the code can be split into separate modules? For instance, a submodule around the code that parses the input files and organises the search results.
This might also include the code that builds the `ObsPack`, `Subfolder`, `StoredData` objects.

An `ObsPack` object could also bring together some of the code into a logical collection, etc.

I'm happy to try to implement some of these suggestions if you don't have time.

Anyway, overall, there is lots of good functionality, but continuing what you started with the `StoredData` objects would bring some nice structure to the code.

2025-02-25 14:38 UTC, rt17603 commented
> The new naming stuff looks really nice.
> 
> There's a lot of code here. I think it might be easier to understand if the code modelled the ObsPack more closely.
> 
> The code could broadly split into two phases:
> 
>     1. parse the search input to make the obspack structure (which would be represented in an `ObsPack` object)
> 
>     2. write out the data
> 
> 
> Obviously this is what the code is already doing, but the point would be to focus on building the obs pack structure in the code using objects. Right now it feels like the structure is encoded in many functions that pass file paths around.
> 
> In addition to your `StoredData` object, you could have a `Collection` object (in the comments, I suggested `ObsPack` and `Subfolder` objects, although they both share some common features) that contains `StoreData` and other `Collection` objects. Basically, the `Collection` object is like a folder, and the `StoredData` object is like a file.
> 
> Also, maybe some of the code can be split into separate modules? For instance, a submodule around the code that parses the input files and organises the search results. This might also include the code that builds the `ObsPack`, `Subfolder`, `StoredData` objects.
> 
> An `ObsPack` object could also bring together some of the code into a logical collection, etc.
> 
> I'm happy to try to implement some of these suggestions if you don't have time.
> 
> Anyway, overall, there is lots of good functionality, but continuing what you started with the `StoredData` objects would bring some nice structure to the code.

I've had similiar thoughts about restructuring to create an `ObsPack` object which came naturally from starting down the `StoredData` route - I think it does make sense.

However, I do think what is here now does work well for the moment and this does add an initial ability to create an obspack which we can then continue to build on. Restructuring as a next step to include these types of internal updates wouldn't need to change the front-facing code too much from what we have here. Overall, I'd like to get this in soon so we can move onto the next steps.

2025-02-25 14:47 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        obspack_path: pathType | None = None,
We do use `pathType` (or `optionalPathType`) in a few places in the code - perhaps we could do a find and replace separately for this if we did want to change this to `str | Path`? Actually though, I do think it's useful having an alias for this as it does get repeated - at least it means we're always allowing a `str` or a `Path` whereas otherwise we may forget and only include one or the other.

2025-02-25 14:49 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    def define_obspack_filename(
It's more that sometimes you may want to call this without overwriting the currently stored value (whether that's via `__init__` or calling the function previously). That happens when you're cycling through creating new names and checking whether they're unique or now. That's why the `add_to_object` bool is included.

2025-02-25 14:51 UTC, rt17603 commented on requirements.txt
> +setuptools
I seem to recall I had an issue where my environment claimed that `setuptools` wasn't available? I can remove it though if we don't think it's needed.

2025-02-25 15:20 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    obspack_name = cast(str, obspack_name)
If `obspack_stub` is `None` and `obspak_name` is `None`, then `obspack_name` will still be `None` at this point, so it shouldn't be cast to `str`.

2025-02-25 15:36 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    Based on the metadata associated with the retrieved data, create suitable obspack
"Add obspack filenames to StoredData objects in retrieved_data" might be a better first line. When I saw this function, my first question was "add the filenames to what?"

2025-02-25 15:44 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +                        # print(f"Checking new names with {additional_key}")
remove print statement

2025-02-25 16:02 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    file_manager = ExitStack()
You need to use `with file_manager: ...` or manually call `file_manager.close()` after you're done using it, otherwise the files aren't closed. 

Since there is only one context you need to enter into, you can just do
```
with importlib.resources.as_file(release_file_ref) as f:
    release_file_path = f
```

2025-02-25 16:03 UTC, brendan-m-murphy commented on requirements.txt
> +setuptools
You need to install setup tools in new virtual environments, so it could be missing for that reason. Does something fail CI if you don't include this requirement?

2025-02-25 16:07 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    # TODO: How do we find out which bucket/store is being used? Is there a default if this is not specified?
I guess in this context it depends on what store the data has come from. I suppose you could make an option for passing the either a metakeys file or a list of potential keys to use to fix conflicts.

2025-02-25 17:11 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        ds.to_netcdf(data.obspack_filename)
if you do `ds.to_netcdf(obspack_path / data.obspack_filename)`, then you won't need to pass `obspack_path` as an argument to many of the other functions, like `add_obspack_filenames`, `define_obspack_filenames`, `define_obspack_filename`

2025-02-25 17:32 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        ds.to_netcdf(data.obspack_filename)
Though I agree this could simplify things, one reason to include `obspack_path` as an input for these functions and not just include this in the `create_obspack` function would be to allow these functions to be called independently and still be able to define the complete filepath to where the file would be stored on disc.

I think this could actually shake out in a potential restructure as we could rely more on the `obspack_path` definition being readily available without having to pass around a variable (e.g. `obspack_path` is already a potential attribute on `StoredData` and could be used in more places). Would have to see.

2025-02-25 17:32 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +                    if np.all(key_present):
Good spot - I'll update that.

2025-02-25 17:33 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +                        # print(f"Checking new names with {additional_key}")
Good spot - my original intention with this was to update this to a logger as I think storing the information that this process occurred could be useful to record. I'll update that.

2025-02-25 17:34 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    Based on the metadata associated with the retrieved data, create suitable obspack
Thanks for the feedback - I'll update this and the other part of the docstring you commented on.

2025-02-25 17:34 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        list: Same list of StoredData objects passed to the function
As commented on the other doc-string comment - I'll include a clarification for that.

2025-02-25 17:36 UTC, brendan-m-murphy requested changes
There are a few things that need to be fixed (the `obspack_name` issue in particular).

Again, I think it would benefit from some tidying, since the same arguments get passed around a lot, and there's a lot of disparate functionality in a single long file. I gave an example where you might avoid passing `obspack_path` to several functions, and a few other suggestions of functionality you might move into `StoredData`.

I think the code is more likely to be improved if it is done now, rather than adding an issue to do it later, unless there is a deadline that requires this functionality now.

2025-02-25 17:36 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    unique_obs_types = np.unique(obs_types)
If you only need the unique obs types, you can use `search_df["obs_type"].unique()`

2025-02-25 17:36 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    filename: pathType | None = None, search_df: pd.DataFrame | None = None, store: str | None = None
I guess this should be `optionalPathType`? Although I prefer it the way it is.

2025-02-25 17:36 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    def __init__(
It seems like passing the subfolder here would simplify a lot of code (since you won't have to pass the subfolder info around). Also possibly "data version"?

2025-02-25 17:36 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    def define_obspack_filename(
Maybe use two different functions, like `make_obspack_filename` and `update_obspack_filename`, which would just use `make_obspack_filename` then set `obspack_filename` to the value.

2025-02-25 17:36 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +def find_data_version(metadata: dict) -> str | None:
Use this to add a method to `StoredData`, or use it in `StoredData.__init__` to add the data version there.

2025-02-25 17:40 UTC, rt17603 commented
> There are a few things that need to be fixed (the obspack_name issue in particular).
Was that the comment from the previous set of comments on `obspack_name` not being a string?

2025-02-25 17:41 UTC, brendan-m-murphy commented
> > There are a few things that need to be fixed (the obspack_name issue in particular).
> 
> Was that the comment from the previous set of comments on `obspack_name` not being a string? That should be fixed now.

Yes, sorry those all should have been on the review.

2025-02-25 17:43 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    unique_obs_types = np.unique(obs_types)
Yeah previously this did need `obs_types` as well but I can simplify that now since this has been updated.

2025-02-25 17:44 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        ds.to_netcdf(data.obspack_filename)
Yea one option would be to make that an attribute of `StoredData`, so the version of `define_obspack_filename` there doesn't need that argument. I mentioned some other changes like that as well (e.g. the subfolder of a `StoredData` object).

2025-02-25 17:45 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    filename: pathType | None = None, search_df: pd.DataFrame | None = None, store: str | None = None
Yes, I know I made the point about using `pathType` before for consistency but I do agree this seems a bit nicer than `optionalPathType`.. I'm a bit torn! I'd be tempted to keep `pathType` but stop using `optionalPathType` and just use `pathType | None`?

2025-02-25 17:53 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +            raise ValueError("When constructing names, unable to find key within supplied dictionary")
I'll add that

2025-02-26 09:11 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    filename: pathType | None = None, search_df: pd.DataFrame | None = None, store: str | None = None
Sure we can just replace `optionalPathType`.

2025-02-28 12:00 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    file_manager = ExitStack()
Ok thanks for this.

So am I right that this is the suggested update for this?
```
    release_file_ref = importlib.resources.files("openghg") / "data/obspack/obspack_README.md"

    with importlib.resources.as_file(release_file_ref) as f:
        release_file_path = f

    release_files = [release_file_path]
    return release_files
```

Using what you included above it looks like the explicit creation of `file_manager` wasn't necessary and this still seems to run ok.

2025-02-28 14:43 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    def __init__(
I've added `subfolder` and `data_version` as attributes for `StoredData` - at the moment they can still be supplied as an input for the other functions though. This is good groundwork for the discussed restructure though.

2025-02-28 14:43 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +def find_data_version(metadata: dict) -> str | None:
I've allowed `data_version` to be extracted from the metadata within `StoredData` now.

2025-02-28 14:44 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    filename: pathType | None = None, search_df: pd.DataFrame | None = None, store: str | None = None
I guess this would be a tidy issue then rather than for this PR as it would impact other parts of the code?

2025-02-28 14:47 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +class StoredData:
I've added this as a comment on the parent issue so this can be tracked for the next version of this code - https://github.com/openghg/openghg/issues/1078

2025-02-28 14:48 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    # TODO: How do we find out which bucket/store is being used? Is there a default if this is not specified?
I'm going to leave this for now - I don't know if we'd want an explicit issue for this but we could look at making sure `get_metakeys` connects to the default internally if we have one.

2025-02-28 14:52 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +def _construct_name(keys: list | str, dictionary: dict, separators: Sequence[str]) -> str:
I'm going to leave this a direct constructor as I think it's a bit more clear about what it's doing but this could be a nice idea to move to - I've added the details to the parent issue #1078

2025-02-28 14:54 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        if isinstance(obspack_filename, str):
For me, I'm not always sure compact syntax like this is the clearest to (mentally) parse.

In this case though, I think this seems clear enough so I've updated that and added some similar statements for other attributes.

2025-02-28 14:54 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    def define_obspack_filename(
I've updated this to use the two different functions as suggested.

2025-02-28 15:29 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    filename: pathType | None = None, search_df: pd.DataFrame | None = None, store: str | None = None
Sure, I don't think it matters much either way. I suspect there will be places where `pathType` isn't used, but maybe should be, etc.

2025-02-28 15:43 UTC, brendan-m-murphy approved these changes
Okay, looks good!

2025-02-28 15:43 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +    def __init__(
Okay seems like a good start. Something I've done in inversions is make the function with all the options start with "_", then make a method of the same name for a class that supplies a lot of the arguments.

2025-02-28 15:43 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        DataRetrieved = StoredData(data_retrieved, obs_type=obs_type)
This should adhere to "lower snake case" format, so maybe `stored_data` or `_data_retrieved`.

2025-02-28 15:43 UTC, brendan-m-murphy commented on openghg/datapack/_obspack.py
> +        DataRetrieved = StoredData(data_retrieved, obs_type=obs_type)
If you could pass the `subfolders` info here, that would mean it doesn't need to be passed elsewhere. (Or maybe add the subfolder info in a separate step after this is called in `create_obspack`

2025-02-28 16:04 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    def __init__(
Sounds like a good convention - were you thinking that `define_obspack_filename` --> `_define_obspack_filename` in the code below then? This may mean a slight tweak to the current tests but that's probably ok for now.

2025-02-28 16:05 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        DataRetrieved = StoredData(data_retrieved, obs_type=obs_type)
Ah yes you're right - because this a list not a class itself:

```suggestion
        stored_data = StoredData(data_retrieved, obs_type=obs_type)
```

2025-02-28 16:08 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +        DataRetrieved = StoredData(data_retrieved, obs_type=obs_type)
I think for the moment I was trying to avoid having to pass `subfolders` to the `retrieve_data` function when this wasn't used in it.

2025-02-28 18:21 UTC, rt17603 commented on openghg/datapack/_obspack.py
> +    def __init__(
I think for now I'll keep the naming as is (the methods are a different name now than the functions anyway) - but I think if we come up with conventions like that we should start recording them in the style-guide for developers so we can make sure to apply it consistently.

2025-03-03 09:23 UTC, brendan-m-murphy approved these changes
Looks good!

2025-03-03 09:25 UTC, merged