Updated edgar transform to work with monthly files
openghg/openghg pull request #1187
Opened 2024-11-22 17:22 UTC by brendan-m-murphy

* **Summary of changes** (Bug fix, feature, docs update, ...)

Updated EDGAR transform code to accept monthly flux files.

* **Please check if the PR fulfills these requirements**

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [ ] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

2025-10-02 14:11 UTC, rt17603 commented
@brendan-m-murphy will create a small issue for this so we can keep track

2026-03-12 15:17 UTC, brendan-m-murphy commented
@copilot+gpt-5.3-codex open a PR off this branch to merge in devel. Make sure you git-blame/check old PRs to see why this diverged from devel, and ideally find a solution that keeps both current and incoming improvements.

2026-03-13 10:44 UTC, brendan-m-murphy commented
@copilot add a realistic test for the monthly EDGAR parsing. Here is part of an ncdump of a real file (stored at .../Gridded_fluxes/CH4/EDGAR_v8.0/monthly_sectoral/AGRICULTURE/EDGAR_2024_GHG_CH4_2001_AGRICULTURE_flx.nc)

ncdump -c with grep -v to remove all but the first lines of the lat/lon coordinates:

netcdf EDGAR_2024_GHG_CH4_2001_AGRICULTURE_flx {
dimensions:
	lat = 1800 ;
	lon = 3600 ;
	time = 12 ;
variables:
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
	float time(time) ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
		time:units = "days since 2001-01-01 00:00:00" ;
	float fluxes(time, lat, lon) ;
		fluxes:_FillValue = NaNf ;
		fluxes:substance = "CH4" ;
		fluxes:year = "2001" ;
		fluxes:release = "EDGARv2024ghg" ;
		fluxes:long_name = "Agriculture" ;
		fluxes:description = "Agriculture" ;
		fluxes:ChunkSizes = 1LL, 1800LL, 3600LL ;
		fluxes:units = "kg m-2 s-1" ;

// global attributes:
		:description = "Agriculture" ;
		:institution = "European Commission, Joint Research Centre" ;
		:source = "https://edgar.jrc.ec.europa.eu/dataset_ghg2024" ;
		:how_to_cite = "https://edgar.jrc.ec.europa.eu/dataset_ghg2024#howtocite" ;
		:copyright_notice = "https://edgar.jrc.ec.europa.eu/dataset_ghg2024#conditions" ;
		:contacts = "https://edgar.jrc.ec.europa.eu/dataset_ghg2024#info JRC-EDGAR@ec.europa.eu" ;
		:units = "kg m-2 s-1" ;
data:

 lat = -89.95, -89.85, -89.75, -89.65, -89.55, -89.45, -89.35, -89.25, 
    -9.95, -9.85, -9.75, -9.65, -9.55, -9.45, -9.35, -9.25, -9.15, -9.05, 
    -8.95, -8.85, -8.75, -8.65, -8.55, -8.45, -8.35, -8.25, -8.15, -8.05, 
    -7.95, -7.85, -7.75, -7.65, -7.55, -7.45, -7.35, -7.25, -7.15, -7.05, 
    -6.95, -6.85, -6.75, -6.65, -6.55, -6.45, -6.35, -6.25, -6.15, -6.05, 
    -5.95, -5.85, -5.75, -5.65, -5.55, -5.45, -5.35, -5.25, -5.15, -5.05, 
    -4.95, -4.85, -4.75, -4.65, -4.55, -4.45, -4.35, -4.25, -4.15, -4.05, 
    -3.95, -3.85, -3.75, -3.65, -3.55, -3.45, -3.35, -3.25, -3.15, -3.05, 
    -2.95, -2.85, -2.75, -2.65, -2.55, -2.45, -2.35, -2.25, -2.15, -2.05, 
    -1.95, -1.85, -1.75, -1.65, -1.55, -1.45, -1.35, -1.25, -1.15, -1.05, 
    -0.95, -0.85, -0.75, -0.65, -0.55, -0.45, -0.35, -0.25, -0.15, -0.05, 
    0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.05, 1.15, 
    1.25, 1.35, 1.45, 1.55, 1.65, 1.75, 1.85, 1.95, 2.05, 2.15, 2.25, 2.35, 
    2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05, 3.15, 3.25, 3.35, 3.45, 3.55, 
    3.65, 3.75, 3.85, 3.95, 4.05, 4.15, 4.25, 4.35, 4.45, 4.55, 4.65, 4.75, 
    4.85, 4.95, 5.05, 5.15, 5.25, 5.35, 5.45, 5.55, 5.65, 5.75, 5.85, 5.95, 
    6.05, 6.15, 6.25, 6.35, 6.45, 6.55, 6.65, 6.75, 6.85, 6.95, 7.05, 7.15, 
    7.25, 7.35, 7.45, 7.55, 7.65, 7.75, 7.85, 7.95, 8.05, 8.15, 8.25, 8.35, 
    8.45, 8.55, 8.65, 8.75, 8.85, 8.95, 9.05, 9.15, 9.25, 9.35, 9.45, 9.55, 
    9.65, 9.75, 9.85, 9.95, 10.05, 10.15, 10.25, 10.35, 10.45, 10.55, 10.65, 

 lon = -179.95, -179.85, -179.75, -179.65, -179.55, -179.45, -179.35, 
    -9.05, -8.95, -8.85, -8.75, -8.65, -8.55, -8.45, -8.35, -8.25, -8.15, 
    -8.05, -7.95, -7.85, -7.75, -7.65, -7.55, -7.45, -7.35, -7.25, -7.15, 
    -7.05, -6.95, -6.85, -6.75, -6.65, -6.55, -6.45, -6.35, -6.25, -6.15, 
    -6.05, -5.95, -5.85, -5.75, -5.65, -5.55, -5.45, -5.35, -5.25, -5.15, 
    -5.05, -4.95, -4.85, -4.75, -4.65, -4.55, -4.45, -4.35, -4.25, -4.15, 
    -4.05, -3.95, -3.85, -3.75, -3.65, -3.55, -3.45, -3.35, -3.25, -3.15, 
    -3.05, -2.95, -2.85, -2.75, -2.65, -2.55, -2.45, -2.35, -2.25, -2.15, 
    -2.05, -1.95, -1.85, -1.75, -1.65, -1.55, -1.45, -1.35, -1.25, -1.15, 
    -1.05, -0.95, -0.85, -0.75, -0.65, -0.55, -0.45, -0.35, -0.25, -0.15, 
    -0.05, 0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.05, 
    1.15, 1.25, 1.35, 1.45, 1.55, 1.65, 1.75, 1.85, 1.95, 2.05, 2.15, 2.25, 
    2.35, 2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05, 3.15, 3.25, 3.35, 3.45, 
    3.55, 3.65, 3.75, 3.85, 3.95, 4.05, 4.15, 4.25, 4.35, 4.45, 4.55, 4.65, 
    4.75, 4.85, 4.95, 5.05, 5.15, 5.25, 5.35, 5.45, 5.55, 5.65, 5.75, 5.85, 
    5.95, 6.05, 6.15, 6.25, 6.35, 6.45, 6.55, 6.65, 6.75, 6.85, 6.95, 7.05, 
    7.15, 7.25, 7.35, 7.45, 7.55, 7.65, 7.75, 7.85, 7.95, 8.05, 8.15, 8.25, 
    8.35, 8.45, 8.55, 8.65, 8.75, 8.85, 8.95, 9.05, 9.15, 9.25, 9.35, 9.45, 
    9.55, 9.65, 9.75, 9.85, 9.95, 10.05, 10.15, 10.25, 10.35, 10.45, 10.55, 

 time = 14, 45, 73, 104, 134, 165, 195, 226, 257, 287, 318, 348 ;
}


The lat/lon is called the "globaledgar" domain in OpenGHG. From the readme https://edgar.jrc.ec.europa.eu/readme/edgar_2024_ghg_readme.txt you can see that the lat/lon increment is 0.1 (degrees are the units), from the part I pasted above, you can see the initial values, and from the dimensions you can see how many values there are, so you should be able to reconstruct the coordinates.

Perhaps the simplest way to set-up this test would be to construct an xarray Dataset matching the description above, save it to a temporary directory using the file name/paths above (the "parse edgar" code works off of an "EDGAR directory"), and then run transform_flux. You can also unit test smaller parts of the code with this dataset and/or file name.

2026-03-17 14:40 UTC, brendan-m-murphy commented on CHANGELOG.md
> +- Fixed EDGAR parsing for monthly sectoral files by normalising `latitude`/`longitude` coordinates to `lat`/`lon` and raising a clear error when the EDGAR version cannot be inferred from the filename
The changelog links to the PR not the issue.

2026-03-17 14:47 UTC, brendan-m-murphy commented on openghg/transform/_regrid.py
> +            data = data.copy(data=np.ascontiguousarray(values))
This could be mapped over chunks if the backend is Dask and the chunks are np.ndarray. Here is a similar function from openghg_inversions (https://github.com/openghg/openghg_inversions/blob/5994a39a9359e479f9e77b8f414a59bbc2eb2997/openghg_inversions/array_ops.py#L190):

```python
def to_dense(da: xr.DataArray) -> xr.DataArray:
    """Convert sparse to numpy.

    If the data array has chunks, these are preserved, but the underlying arrays are converted.
    Does nothing if chunks are already numpy.
    """
    if not isinstance(da.data, DaskArray):  # type: ignore
        return da.as_numpy()

    # check chunk types
    if isinstance(da.data._meta, SparseArray):
        # hack to apply the Sparse `todense()` method to chunks
        return xr.apply_ufunc(_sparse_dask_to_dense, da, dask="allowed")

    return da
```

2026-03-17 15:01 UTC, brendan-m-murphy commented on openghg/util/_time.py
> +
This is a rough check, so maybe just adding some tolerance to 28 and 31 would suffice.

2026-03-18 17:16 UTC, SutarPrasad requested changes
small changes related to day calculations

2026-03-18 17:16 UTC, SutarPrasad commented on openghg/util/_time.py
> +    min_month_ns = 28 * 24 * 60 * 60 * 1_000_000_000
```suggestion
    min_month_ns = np.timedelta64(28, 'D')
```

2026-03-18 17:16 UTC, SutarPrasad commented on openghg/util/_time.py
> +    max_month_ns = 31 * 24 * 60 * 60 * 1_000_000_000
```suggestion
    max_month_ns = np.timedelta64(31, 'D')
```

2026-03-18 17:16 UTC, SutarPrasad commented on openghg/util/_time.py
> +    min_month_ns = 28 * 24 * 60 * 60 * 1_000_000_000
np.timedelta64(28, 'D').astype('timedelta64[ns]') == np.timedelta64(2419200000000000,'ns')

2026-03-19 09:08 UTC, brendan-m-murphy commented on openghg/util/_time.py
> +    max_month_ns = 31 * 24 * 60 * 60 * 1_000_000_000
That doesn't quite work since we cast to int64... so it needs to be something like `np.timedelta64(np.timedelta(31, "D")).astype("int64")`, but maybe I can avoid converting to int before the `np.diff`.

2026-03-19 09:08 UTC, brendan-m-murphy commented on openghg/util/_time.py
> +    max_month_ns = 31 * 24 * 60 * 60 * 1_000_000_000
Ah I see you did something like this in the previous comment.

2026-04-14 14:58 UTC, brendan-m-murphy commented
@SutarPrasad this is ready for re-review (I implemented the changes you suggested).

2026-04-30 13:39 UTC, SutarPrasad approved these changes

2026-04-30 14:09 UTC, ben-westhenry approved these changes
All looks good

2026-04-30 14:09 UTC, merged