Add boundary conditions and standardise field and timed data storage
openghg/openghg pull request #299
Opened 2022-04-01 13:52 UTC by rt17603

Adding new `BoundaryConditions` class to allow boundary conditions data (vertical curtains around a lat-lon domain) to be added to the object store. Tests have been added for this (based on those present within "test_emissions.py")

As a part of this the following additional changes have been made:
 - Within "_datasource.py" the `Datasource.add_timeseries` and `Datasource.add_field_data` (and derived) methods have been merged into one `Datasource.add_timed_data` method which is currently called when "time" is a coordinate within our data.
    - This method now adds the extent period (e.g. sampling_period or time_period) to the end_date to make sure the label covers the time *represented* by the data.
    - Note that this will now alter *all* daterange_str values for timeseries and fields data (the tests have been updated to reflect this). The only case where this will not change is if the "sampling_period" is unknown.
 - To code to determine the time period of the data has now been standardised between `BoundaryConditions`, `Emissions` and `Footprints` classes (split out into a separate `_infer_time.py` module)

2022-04-01 15:05 UTC, gareth-j commented
This look great! I might leave it til Monday to start going over it, thanks Friday brain.

2022-04-11 14:19 UTC, gareth-j requested changes
Looks great! Just a few small changes and it should be ready to merge.

2022-04-11 14:19 UTC, gareth-j commented on openghg/store/_footprints.py
> +    def lookup_uuid(self, site: str, domain: str, model: str, height: str) -> Union[str, bool]:
This can be removed

2022-04-11 14:19 UTC, gareth-j commented on openghg/store/_footprints.py
> +    def set_uuid(self, site: str, domain: str, model: str, height: str, uuid: str) -> None:
This can be removed

2022-04-11 14:19 UTC, gareth-j commented on openghg/store/_infer_time.py
> +        str, str, str:
The type hint and return value here are different.

2022-04-11 14:19 UTC, gareth-j commented on tests/store/test_boundary_conditions.py
> +def test_set_lookup_uuids():
This can be removed

2022-04-11 15:02 UTC, rt17603 commented on openghg/store/_boundary_conditions.py
> +    def format() -> dict:
Ok - I'll update this to Dict[str, Any]

2022-04-11 15:25 UTC, rt17603 commented on openghg/store/_boundary_conditions.py
> +    def lookup_uuid(self, species: str, bc_input: str, domain: str, date: str) -> Union[str, bool]:
Removed `lookup_uuid` method for boundary conditions

2022-04-11 15:27 UTC, rt17603 commented on tests/store/test_boundary_conditions.py
> +def test_set_lookup_uuids():
Removed

2022-04-11 15:36 UTC, gareth-j approved these changes
Looks good.

2022-04-11 15:44 UTC, merged