Harmonising get functions to produce same errors
openghg/openghg pull request #444
Opened 2022-10-07 13:50 UTC by rt17603

Ensuring behaviour for openghg.retrieve.get_* functions is consistent and adding custom `SearchError` function for openghg
 - If no results found returns a `SearchError` with helpful message (restates keys which were passed in)
 - If multiple results are found returns `SearchError` with helpful message (compares metadata and prints differences)
 - All functions (including get_obs_surface_local) are now fed through _get_generic function

Closes #297, #416

2022-10-07 14:25 UTC, rt17603 commented
@gareth-j - not sure about this build documentation error? Seems to be unable to find a some of the sphinx documentation modules?

```
ModuleNotFoundError: No module named 'sphinx_togglebutton'

make: *** [Makefile:34: html] Error 2
Error: Process completed with exit code 2. 
```

2022-10-19 14:24 UTC, gareth-j requested changes
Looks good, maybe we can just move the new exceptions to `openghg.types`.

2022-10-19 14:24 UTC, gareth-j commented on openghg/exceptions/__init__.py
> +class OpenGHGError(Exception):
These could be moved to `openghg.types` as we've already got some custom exceptions there.

2022-10-20 09:15 UTC, gareth-j commented
I think this looks good and can be merged.

2022-10-20 09:17 UTC, rt17603 commented
Great, would you be able to give this an approve? Then I'll get it merged.

2022-10-20 12:53 UTC, gareth-j approved these changes
Looks good.

2022-10-20 12:55 UTC, merged