2. Add explicit modes for adding and updating data
openghg/openghg pull request #680
Opened 2023-06-13 09:36 UTC by rt17603

This is 2 of 3 in a series of PRs to apply the updates discussed in #591. This overall change will update how adding data is treated in the object store.

This PR includes the following changes:

 - Adds in functionality with additional flags:
     -  `if_exists` to deal with situations where new data overlaps the same time period as current data
         - None (default) - concatenate new and previous data if there is no time overlap, raise error if new data overlaps previous time period.
         - "new" - just include new data
         - "replace" - *incorporate data into previous data timeseries - this will be more fully implemented in the 3rd PR*
    - `save_current` to deal with question around versioning
       - None (default) - use current version if possible but create new version if data is being changed (i.e. in most cases where if_exists is "new" or "replace")
       - True - save current data and create a new version
       - False - overwrite current data with new data and don't create a new version
    - `force` - whether to replace data even if this is identical to previous (covers previous overwrite case and useful for tests)
 - `overwrite` flag is deprecated - will use `if_exists="new"`
 - Data stored in the object store can be now be deleted as part of adding new data. This is dependent on the situation and flags passed. This creates a short term back up of the current data, writes the new data and then deletes the back up data if the write is successful.

Tests added/updated to check this in db_integrity/test_data_updates.py:

    test_obs_data_read_header_diff
        updated to make this a fail case and to check for DataOverlapError
    test_obs_data_read_header_diff_update
        added/updated to check this runs with overwrite=True and to check internal versioning is updated correctly.
    test_obs_data_read_two_frequencies
        updated to check internal versioning for data stored as different data sources (should be v1 for both)

*These are being merged into the 'new_object_store' branch for now as a parallel branch as part of the "Special Release" milestone. This branch will then be merged into 'devel' in one go when ready. This also means the CI isn't being run by default but will be run when the overall PR is created against devel.*

2023-07-13 10:07 UTC, gareth-j requested changes
I think this will add some good functionality but needs to use the functios within the `objectstore` submodule to be handling objects in the store instead of using path handling directly.
I'm also not sure I like the use of the `None` as a value for the `if_exists` and `save_current` values. Could these two keyword arguments be combined? At the moment it feels a bit confusing and could lead to bugs if the logic isn't 100% correct.

2023-07-13 10:50 UTC, rt17603 commented
> I think this will add some good functionality but needs to use the functios within the `objectstore` submodule to be handling objects in the store instead of using path handling directly. I'm also not sure I like the use of the `None` as a value for the `if_exists` and `save_current` values. Could these two keyword arguments be combined? At the moment it feels a bit confusing and could lead to bugs if the logic isn't 100% correct.

- Yeah figuring out how to find the stored objects was one of the tricker parts. Happy to use `objectstore` submodule as needed for path handling - this was originally based on the save module was finding the stored objects but sounds like there is new functionality which now does this better.
- For use of `None` perhaps we could have a third keyword argument instead if you feel this is unclear? The main thing is to make sure there is a default set of steps followed if no options are specified.
- I had a lot of discussions including with Joe around how to describe the process and splitting out the two ideas into separate keywords was the best option we found. I don't think combining these back together would make this less confusing. I think overall it's just a complex set of options we've having to allow for to satisfy both clarity and practicality.

I would point to the design issue around this where I summarised details of discussion and reasoning for the steps chosen https://github.com/openghg/openghg/issues/591.

2023-07-13 10:54 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +                - None - checks new and current data for timeseries overlap
Sure - what do you think would work as a default for this instead? Perhaps if_exists="fail" or "error"?

2023-07-13 10:58 UTC, rt17603 commented on openghg/util/_versions.py
> +    if if_exists is None and save_current is None:
I included an answer to the general PR response as well but see also issue #591 for discussion around why these arguments were separated out. I would say they end of both being needed to allow for practicality as well as clarity really.

2023-07-13 11:00 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +            bool: True is all deleted, False otherwise
Yeah - I briefly forayed into changing this to a bool but then had to switch it back as it didn't play nicely with the cloud aspects - this doc string is one I missed so can change that back.

2023-07-13 11:10 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +            version_folder = Path(bucket) / version_key
That's fine - this was largely all based on how this was done previously within the `save` function e.g. https://github.com/openghg/openghg/blob/devel/openghg/store/base/_datasource.py#L614
```
data_key = f"{Datasource._data_root}/uuid/{self._uuid}/{version_str}/{daterange}"
```
So how would you want to update that do you think? Would you want to try and incorporate this into `objectstore` in some way perhaps?

2023-07-13 13:26 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +            if version_folder.exists() and not new_version:
From discussion sounds like this is addressed within the __init__.py

2023-07-19 17:14 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +            bool: True is all deleted, False otherwise
Seems to have been updated anyway as part of merging from devel

2023-07-19 17:19 UTC, rt17603 commented
@gareth-j - As discussed last week, would you be able to add the explicit changes requested around the datasource key and the save function? If you recall, I followed the original setup present within the `Datasource.save()` but it sounds like `objectstore` supercedes that now so it would be helpful if you could point me to what you would like me to change this to.

2023-07-20 09:39 UTC, gareth-j commented
Yeah sure, I'll try and get that done today.

2023-08-31 15:44 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +            version_folder = Path(bucket) / version_key
This should now be covered by PR #722

2023-08-31 15:45 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +            if version_folder.exists() and not new_version:
This should now be addressed by #722

2023-09-07 12:17 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +                filepath = version_folder / f"{daterange}._data"
Updated within PR #722

2023-09-07 12:17 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +                    os.rmdir(version_folder_backup)
Has been updated through PR #722

2023-09-07 12:18 UTC, rt17603 commented on openghg/store/base/_datasource.py
> +                version_folder_backup = Path(bucket) / version_key_backup
Has been updated through PR #722

2023-09-12 09:32 UTC, gareth-j requested changes
Just a few changes for passing in keyword arguments, otherwise looks good!

2023-09-12 09:32 UTC, gareth-j commented on openghg/store/_emissions.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
```suggestion
        new_version = check_if_need_new_version(if_exists=if_exists, save_current=save_current)
```

2023-09-12 09:32 UTC, gareth-j commented on openghg/store/_emissions.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
```suggestion
        new_version = check_if_need_new_version(if_exists=if_exists, save_current=save_current)
```

2023-09-12 09:32 UTC, gareth-j commented on openghg/store/_eulerian_model.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
```suggestion
        new_version = check_if_need_new_version(if_exists=if_exists, save_current=save_current)
```

2023-09-12 09:32 UTC, gareth-j commented on openghg/store/_footprints.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
```suggestion
        new_version = check_if_need_new_version(if_exists=if_exists, save_current=save_current)
```

2023-09-12 09:32 UTC, gareth-j commented on openghg/store/_obscolumn.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
```suggestion
        new_version = check_if_need_new_version(if_exists=if_exists, save_current=save_current)
```

2023-09-12 09:32 UTC, gareth-j commented on openghg/store/_obssurface.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
```suggestion
        new_version = check_if_need_new_version(if_exists=if_exists, save_current=save_current)
```

2023-10-02 09:34 UTC, gareth-j commented on openghg/store/_emissions.py
> +        new_version = check_if_need_new_version(if_exists, save_current)
Yeah all good, we don't need to be too pedantic about it for functions with < 3 arguments.

2023-10-02 09:44 UTC, gareth-j approved these changes
Looks good!

2023-10-02 10:03 UTC, merged