added black check in the CI before lint
openghg/openghg pull request #768
Opened 2023-08-31 09:49 UTC by SutarPrasad

* **Summary of changes** (Bug fix, feature, docs update, ...)

     - Added black format check before lint check in the CI.

* **Please check if the PR fulfills these requirements**

- [x] Closes #719  (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [x] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [x] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

2023-09-06 14:31 UTC, gareth-j requested changes
I think we could use `--check`, other than that looks good!

2023-09-06 14:31 UTC, gareth-j commented on .github/workflows/workflow.yaml
> +          black --diff --line-length 110 openghg/
```suggestion
          black --check --line-length 110 openghg/
```

2023-09-08 09:51 UTC, SutarPrasad commented
Demo output of the --check for reference.
<img width="823" alt="image" src="https://github.com/openghg/openghg/assets/75735315/efe0ddeb-743f-4290-b87a-8d8f858a7c50">

Link to docs for understanding the exit codes : https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#check

2023-09-11 16:09 UTC, SutarPrasad commented
> I think we could use `--check`, other than that looks good!

It's done

2023-09-12 09:33 UTC, gareth-j approved these changes
Looks good!

2023-09-13 08:44 UTC, merged