added env dev and one documentation file
openghg/openghg pull request #769
Opened 2023-08-31 12:16 UTC by SutarPrasad

* **Summary of changes** (Bug fix, feature, docs update, ...)
Added environment-dev.yaml file. Updated one documentation.

* **Please check if the PR fulfills these requirements**

- [ ] Closes #699 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [ ] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

2023-09-01 11:17 UTC, SutarPrasad commented
demo output
<img width="954" alt="image" src="https://github.com/openghg/openghg/assets/75735315/91076a34-3373-495b-8690-14d718e590b6">

2023-09-04 08:59 UTC, brendan-m-murphy requested changes
Looks good, just needs an entry in the change log.

2023-09-06 14:22 UTC, gareth-j requested changes
Just need to add in `openghg`'s dependencies

2023-09-08 11:40 UTC, SutarPrasad commented on environment-dev.yaml
> +dependencies:
done

2023-09-08 11:40 UTC, SutarPrasad commented on environment-dev.yaml
> +  - types-paramiko
done

2023-09-08 11:45 UTC, brendan-m-murphy approved these changes
Looks good!

2023-09-08 12:05 UTC, brendan-m-murphy approved these changes
Looks like nothing changed from the last review I gave, so still happy to approve this.

2023-09-12 08:45 UTC, brendan-m-murphy submitted a review, later dismissed
Okay, looks good

2023-09-12 08:49 UTC, gareth-j approved these changes

2023-09-12 08:49 UTC, gareth-j commented on CHANGELOG.md
> +- Added environment-dev.yaml file for cloud developers environment, especially dependencies like pytest, pytest-mock requested by users. - [PR #769](https://github.com/openghg/openghg/pull/769)
```suggestion
- Added `environment-dev.yaml` file for developer conda environment - [PR #769](https://github.com/openghg/openghg/pull/769)
```

2023-09-12 09:02 UTC, brendan-m-murphy approved these changes
Looks good!

2023-09-12 09:32 UTC, merged