configuration_file to specify tinydb or mongodb
openghg/openghg pull request #800
Opened 2023-10-02 12:24 UTC by SutarPrasad

* **Summary of changes** (Bug fix, feature, docs update, ...)

    Created a configuration file that specifies the version and mentions 2 database types `tinyBD` and `mongoDB`.
    The connection string for MongoDB or config file path for tiny DB configuration is not added as they are unknown.

* **Please check if the PR fulfills these requirements**

- [ ] Closes #757 (Replace xxxx with the Github issue number)
- [ ] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

Not required

- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [ ] Documentation and tutorials updated/added
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

2023-10-12 14:01 UTC, brendan-m-murphy commented
The format of the config file looks like it could work, but we need code to generate and use it. @gareth-j is this part of another issue?

2023-10-12 14:12 UTC, gareth-j requested changes
Should change to TOML and remove the tinydb section.

2023-10-12 14:12 UTC, gareth-j commented on openghg/db_config.yaml
> +config_version: ""
I think this should be a TOML file instead of YAML as it's cleaner.

2023-10-12 14:12 UTC, gareth-j commented on openghg/db_config.yaml
> +    file_path: "tinydb config file"
We don't need the filepath for the tinydb database as this will be in the object store. I think we'll only need config information for mongodb.

2023-10-31 10:35 UTC, SutarPrasad commented
> > The format of the config file looks like it could work, but we need code to generate and use it. @gareth-j is this part of another issue?
> 
> No, I was just working on the zarr stuff and realised this. @SutarPrasad we also need functions to
> 
>     * read the config file
> 
>     * check correctness of the config file
> 
>     * write to the config file (but I don't think we necessarily need a command line interface as with the user config setup)
> 
>     * documentation on how to create the file, we'll need a new section in the docs for this

Created new issue for this https://github.com/openghg/openghg/issues/814

2023-11-14 10:32 UTC, gareth-j commented
> > > The format of the config file looks like it could work, but we need code to generate and use it. @gareth-j is this part of another issue?
> > 
> > 
> > No, I was just working on the zarr stuff and realised this. @SutarPrasad we also need functions to
> > ```
> > * read the config file
> > 
> > * check correctness of the config file
> > 
> > * write to the config file (but I don't think we necessarily need a command line interface as with the user config setup)
> > 
> > * documentation on how to create the file, we'll need a new section in the docs for this
> > ```
> 
> Created new issue for this #814

I think we should keep all the read/write functionality as part of this PR. We don't want to add a TOML file to the openghg folder, it should be created in the root of the object store itself as it will be user independent.

So what we need is:

1. A function to create an empty config file in the root of an object store, where the object store path is given by the user
   1a. Optionally an interactive setup like we've got for `openghg --quickstart`, could be something like `openghg --setup-store` and have a few options for user input
3. A function to read the config file from the object store
4. Documentation added to the README and getting started documentation for setting the configuration file
5. Tests added for the reading and writing functions

2023-11-14 10:34 UTC, gareth-j requested changes
This needs a bit more work before it's ready.

2023-11-14 10:34 UTC, gareth-j commented on openghg/db_config.toml
The format looks good but this file should be created by a function, not added to the `openghg` folder.

2023-11-30 15:51 UTC, gareth-j commented
I think we can bump this from 0.7.0 as it's not required until we implement the mongodb code. Thoughts @rt17603  and @brendan-m-murphy ?

2024-05-13 13:06 UTC, gareth-j commented
I think this needs completely revisiting when MongoDB is being worked on. To tidy things up I'll close this.

2024-05-13 13:06 UTC, closed without merging