Release `0.7.1`
openghg/openghg pull request #938
Opened 2024-02-29 16:35 UTC by gareth-j

* **Summary of changes** (Bug fix, feature, docs update, ...)

This is a patch release before we do the bigger `0.8.0` release.

## [0.7.1] - 2024-02-29

### Fixed

- Bug fix for conversion of species parameter with its synonym value inside get_obs_surface_local. [PR #871](https://github.com/openghg/openghg/pull/871)
- Bug fix for allowing a period to be specified when this cannot be inferred from the input data [PR #899](https://github.com/openghg/openghg/pull/899)

2024-02-29 16:37 UTC, rt17603 commented
Do we want to get the fix for #937 into `devel` before we do this patch release?

2024-02-29 16:39 UTC, gareth-j commented
> Do we want to get the fix for #937 into `devel` before we do this patch release?

Yeah, we'll merge that before this goes in

2024-02-29 16:41 UTC, rt17603 commented
Sorry I meant #935 - the `test_standardise_obs_openghg` test

2024-03-01 10:13 UTC, rt17603 commented on openghg/dataobjects/_datamanager.py
> +    res = search(data_type=data_type, store=store, **kwargs)
This seems to have been an additional bug fix: #859 which should be added to the CHANGELOG.md

2024-03-01 10:17 UTC, rt17603 commented on environment.yaml
> +  - filelock
Another small update to add to the CHANGELOG.md: #857

2024-03-01 10:19 UTC, rt17603 requested changes
I believe there are 2 additional PR fixes to add to the CHANGELOG.md details but other than that this looks good to go. Tests pass for me locally.

2024-03-01 16:36 UTC, rt17603 approved these changes

2024-03-01 16:52 UTC, milliams approved these changes

2024-03-01 17:09 UTC, merged