Add code to convert old store to zarr store
openghg/openghg pull request #967
Opened 2024-03-26 14:58 UTC by gareth-j

* **Summary of changes** 

This adds in some functionality to convert an old style object store to the new Zarr format. This uses some of Brendan's code for the lookup of arguments etc but I've modified it so it just takes everything in an object store and converts it.
It may be a bit temperamental and I've added some log warnings to tell people it's better to just repopulate using the original data. I've also added a short tutorial to cover how to use the new function.

* **Please check if the PR fulfills these requirements**

- [ ] Closes #964
- [ ] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [ ] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

2024-03-26 16:06 UTC, brendan-m-murphy requested changes
Looks good! Just a few small suggestions for convert function.

2024-03-26 16:06 UTC, brendan-m-murphy commented on openghg/standardise/surface/_openghg.py
> +    print(metadata_initial)
Is this for debugging?

2024-03-27 07:54 UTC, gareth-j commented on openghg/store/storage/_convert.py
> +                    raise ValueError("No data versions found for this search result.")
Done.

2024-03-27 07:56 UTC, gareth-j commented on openghg/store/storage/_convert.py
> +                if not isinstance(v, bool) and v.lower() in tf_none:
Ah yeah good catch.

2024-03-27 07:59 UTC, gareth-j commented on openghg/store/storage/_convert.py
> +                    logger.warning(f"Data overlap error for record {uuid}")
Done.

2024-03-27 07:59 UTC, gareth-j commented on openghg/standardise/surface/_openghg.py
> +    print(metadata_initial)
Oops! Removed.

2024-03-27 10:11 UTC, brendan-m-murphy approved these changes
Looks good! (There's a typo in an error message, but hopefully you can just commit the suggestion and merge)

2024-03-27 10:11 UTC, brendan-m-murphy commented on openghg/store/storage/_convert.py
> +                        f"Unable to find a data sversion for {data_type} data with UUID {uuid}, skipping..."
```suggestion
                        f"Unable to find a data version for {data_type} data with UUID {uuid}, skipping..."
```

2024-03-27 10:46 UTC, merged